image: ubuntu:18.04

build:
  stage: build
  before_script:
    - echo -e "deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse \ndeb-src http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse  \ndeb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse  \ndeb-src http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse  \ndeb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse  \ndeb-src http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse  \ndeb http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse  \ndeb-src http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse\ndeb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse  \ndeb-src http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse \n" > /etc/apt/sources.list && cat /etc/apt/sources.list
    - apt update && apt -y install sudo git make autoconf cmake
  script:
    - cmake .
    - make
  artifacts:
    paths:
      - build/*
